# build-blog.ps1
# Scan src/post for .md files and img/gallery for images,
# then generate src/post/posts.js and img/gallery/gallery.js manifests.
# Pure PowerShell, no Node/npm required, works offline.

$ErrorActionPreference = 'Stop'

# Project root = parent of this script's folder
$root       = Split-Path -Parent $PSScriptRoot
$postDir    = Join-Path $root 'src\post'
$galleryDir = Join-Path $root 'img\gallery'

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-File($path, $text) {
    [System.IO.File]::WriteAllText($path, $text, $utf8NoBom)
}

# ---------- 1. Posts manifest ----------
# 分类规则：
#   扫描 src/post 下所有 .md（递归）
#   - 位于 src\post\notes\ 中的文件 -> 随笔 (essay)
#   - 其余（src\post 根目录）     -> 知识库 (kb)
Write-Host "Scanning posts: $postDir"
$posts = @()

if (Test-Path $postDir) {
    Get-ChildItem -Path $postDir -Recurse -Filter *.md -File | ForEach-Object {
        # Cast to plain [string] so PS note-properties (PSPath, ReadCount, ...) are dropped
        $raw   = [string](Get-Content -Path $_.FullName -Raw -Encoding UTF8)
        $lines = $raw -split "`r?`n"

        # Title: first "# xxx" line, else file name
        $title = $_.BaseName
        foreach ($line in $lines) {
            if ($line -match '^\s*#\s+(.+?)\s*$') { $title = $Matches[1]; break }
        }

        # Excerpt: first non-empty, non-heading, non-divider line, stripped of md marks
        $excerpt = ''
        foreach ($line in $lines) {
            $t = $line.Trim()
            if ($t -eq '' -or $t -match '^#' -or $t -match '^[-*_]{3,}$') { continue }
            $excerpt = ($t -replace '[`*_>#\[\]]', '').Trim()
            break
        }
        if ($excerpt.Length -gt 80) { $excerpt = $excerpt.Substring(0, 80) + '...' }

        # Tags: first 4 "## xxx" section headings, stripped of md marks
        $tags = @()
        foreach ($line in $lines) {
            if ($line -match '^\s*##\s+(.+?)\s*$') {
                $tag = ($Matches[1] -replace '[`*_>#\[\]]', '').Trim()
                if ($tag) { $tags += $tag }
                if ($tags.Count -ge 4) { break }
            }
        }

        # Reading minutes: ~500 chars per minute (CJK)
        $mins = [Math]::Max(1, [Math]::Ceiling($raw.Length / 500.0))

        # Kind: notes 子目录为随笔，其余为知识库
        $isEssay = $_.FullName -like (Join-Path $postDir 'notes\*') -or $_.FullName -like '*\notes\*'
        $kind    = if ($isEssay) { 'essay' } else { 'kb' }
        $kindLabel = if ($isEssay) { '随笔' } else { '知识库' }

        $posts += [ordered]@{
            id        = $_.BaseName
            title     = $title
            date      = $_.LastWriteTime.ToString('yyyy-MM-dd')
            excerpt   = $excerpt
            tags      = $tags
            mins      = $mins
            kind      = $kind
            kindLabel = $kindLabel
            content   = $raw
        }
    }
}

# Newest first
$posts = $posts | Sort-Object { $_.date } -Descending

$postsJson = if ($posts.Count -eq 0) { '[]' } else { ConvertTo-Json @($posts) -Depth 6 }
$postsJs   = "// Auto-generated by build.bat. Do not edit by hand.`r`nwindow.POSTS = $postsJson;`r`n"
Write-File (Join-Path $postDir 'posts.js') $postsJs
Write-Host ("  generated {0} post(s) -> src/post/posts.js" -f @($posts).Count)

# ---------- 2. Gallery manifest ----------
Write-Host "Scanning gallery: $galleryDir"
$images = @()
if (Test-Path $galleryDir) {
    Get-ChildItem -Path $galleryDir -File |
        Where-Object { $_.Extension -match '^\.(jpg|jpeg|png|gif|webp|bmp|svg)$' } |
        Sort-Object Name |
        ForEach-Object {
            $images += [ordered]@{
                name = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
                src  = '../img/gallery/' + $_.Name
            }
        }
}

$galleryJson = if ($images.Count -eq 0) { '[]' } else { ConvertTo-Json @($images) -Depth 4 }
$galleryJs   = "// Auto-generated by build.bat. Do not edit by hand.`r`nwindow.GALLERY = $galleryJson;`r`n"
Write-File (Join-Path $galleryDir 'gallery.js') $galleryJs
Write-Host ("  generated {0} image(s) -> img/gallery/gallery.js" -f @($images).Count)

Write-Host "Done."
